version: '3'
services:
  redis:
    image: redis:4.0.10
    restart: always
    ports: 
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  elasticsearch:
    image: elasticsearch:5.6.10
    restart: always
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  webdis:
    image: anapsix/webdis:latest
    ports:
      - 7379:7379
