version: '3'
services:
  redis:
    image: redis:4.0.10
    restart: always
    ports: 
      - 6379:6379
  elasticsearch:
    image: elasticsearch:5.6.10
    restart: always
    ports:
      - 9200:9200
