version: '3'
services:
  elasticsearch-kibana:
    image: nshou/elasticsearch-kibana
    ports:
      - 9200:9200
      - 5601:5601
    volumes:
      - /cognigo/data/elastic:/usr/share/elasticsearch/data/elasticsearch
    restart: always
    environment:
      LOGSPOUT: ignore
  logspout:
    image: rtoma/logspout-redis-logstash:0.1.8
    command: 'redis://redis'
    environment:
      - DEBUG=true
      - LOGSPOUT=ignore

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8003:80"
  logstash:
    image: logstash:2.3.4
    command: 'logstash -f /conf/logstash.conf -v'
    volumes:
      - ./logstash:/conf
    environment:
      - LOGSPOUT=ignore
